# Uncomment the lines and make appropriate changes

steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install'
    args: ['install']
    env:
    - HOME=/root/
    volumes:
    - name: 'home'
      path: /root/
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/socket-backend:${SHORT_SHA}',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/socket-backend']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'socket-backend',
        '--image',
        'gcr.io/$PROJECT_ID/socket-backend:${SHORT_SHA}',
        '--region',
        'us-east1',
        '--platform',
        'managed',
      ]
images:
  - 'gcr.io/$PROJECT_ID/socket-backend'


